"""sync check

Revision ID: 5f87e01acc7d
Revises: ef52ce9d36bc
Create Date: 2026-02-20 01:04:58.540475

"""

from __future__ import annotations

from alembic import op


revision = "5f87e01acc7d"
down_revision = "ef52ce9d36bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_feed_info_feed_id", "feed_info", ["feed_id"], schema="gtfs"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_feed_info_feed_id", "feed_info", schema="gtfs", type_="unique"
    )
    # ### end Alembic commands ###
