"""sync check

Revision ID: ef52ce9d36bc
Revises:
Create Date: 2026-02-20 00:25:48.368354

"""

from __future__ import annotations

from alembic import op
import logging
import sqlalchemy as sa


revision = "ef52ce9d36bc"
down_revision = None
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    def _add_sequence_pk(table: str) -> None:
        seq = f"gtfs.{table}_id_seq"
        logger.info("Create sequence %s", seq)
        op.execute(f"CREATE SEQUENCE IF NOT EXISTS {seq}")
        logger.info("Add id column to %s", table)
        op.add_column(
            table, sa.Column("id", sa.Integer(), nullable=True), schema="gtfs"
        )
        logger.info("Set default sequence on %s.id", table)
        op.execute(
            f"ALTER TABLE gtfs.{table} ALTER COLUMN id SET DEFAULT nextval('{seq}')"
        )
        logger.info("Backfill %s.id", table)
        op.execute(f"UPDATE gtfs.{table} SET id = DEFAULT WHERE id IS NULL")
        logger.info("Set %s.id NOT NULL", table)
        op.alter_column(table, "id", nullable=False, schema="gtfs")
        logger.info("Add primary key on %s.id", table)
        op.create_primary_key(f"pk_{table}", table, ["id"], schema="gtfs")

    logger.info("Agency table updates")
    _add_sequence_pk("agency")
    op.alter_column(
        "agency", "feed_id", existing_type=sa.VARCHAR(), nullable=False, schema="gtfs"
    )
    op.execute(
        "ALTER TABLE gtfs.agency ALTER COLUMN agency_id TYPE INTEGER USING (agency_id::integer)"
    )
    op.alter_column(
        "agency", "agency_id", type_=sa.Integer(), nullable=False, schema="gtfs"
    )
    op.create_index(
        op.f("ix_gtfs_agency_feed_id"),
        "agency",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.create_unique_constraint(
        "uq_agency_feed_agency_id", "agency", ["feed_id", "agency_id"], schema="gtfs"
    )
    logger.info("Calendar table updates")
    _add_sequence_pk("calendar")
    op.alter_column(
        "calendar", "feed_id", existing_type=sa.VARCHAR(), nullable=False, schema="gtfs"
    )
    op.execute(
        "ALTER TABLE gtfs.calendar ALTER COLUMN service_id TYPE INTEGER USING (service_id::integer)"
    )
    op.alter_column(
        "calendar", "service_id", type_=sa.Integer(), nullable=False, schema="gtfs"
    )
    op.create_index(
        op.f("ix_gtfs_calendar_feed_id"),
        "calendar",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.create_unique_constraint(
        "uq_calendar_feed_service_id",
        "calendar",
        ["feed_id", "service_id"],
        schema="gtfs",
    )
    logger.info("Calendar_dates table updates")
    _add_sequence_pk("calendar_dates")
    op.alter_column(
        "calendar_dates",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="gtfs",
    )
    op.create_index(
        op.f("ix_gtfs_calendar_dates_feed_id"),
        "calendar_dates",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.create_unique_constraint(
        "uq_calendar_date_feed_service_date",
        "calendar_dates",
        ["feed_id", "service_id", "date"],
        schema="gtfs",
    )
    logger.info("Feed_info table updates")
    _add_sequence_pk("feed_info")
    op.add_column(
        "feed_info",
        sa.Column("feed_contact_email", sa.String(), nullable=True),
        schema="gtfs",
    )
    op.alter_column(
        "feed_info",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="gtfs",
    )
    op.create_index(
        op.f("ix_gtfs_feed_info_feed_id"),
        "feed_info",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.drop_column("feed_info", "feed_contact_mail", schema="gtfs")
    logger.info("Frequencies table updates")
    _add_sequence_pk("frequencies")
    op.alter_column(
        "frequencies",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="gtfs",
    )
    op.create_index(
        op.f("ix_gtfs_frequencies_feed_id"),
        "frequencies",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    logger.info("Routes table updates")
    _add_sequence_pk("routes")
    op.add_column(
        "routes", sa.Column("route_url", sa.Text(), nullable=True), schema="gtfs"
    )
    op.add_column(
        "routes",
        sa.Column("route_sort_order", sa.Integer(), nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "routes",
        sa.Column("continuous_pickup", sa.Integer(), nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "routes",
        sa.Column("continuous_drop_off", sa.Integer(), nullable=True),
        schema="gtfs",
    )
    op.alter_column(
        "routes", "feed_id", existing_type=sa.VARCHAR(), nullable=False, schema="gtfs"
    )
    op.create_index(
        op.f("ix_gtfs_routes_feed_id"),
        "routes",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.create_unique_constraint(
        "uq_route_feed_route_id", "routes", ["feed_id", "route_id"], schema="gtfs"
    )
    logger.info("Shapes table updates")
    _add_sequence_pk("shapes")
    op.add_column(
        "shapes",
        sa.Column("shape_dist_traveled", sa.Float(), nullable=True),
        schema="gtfs",
    )
    op.alter_column(
        "shapes", "feed_id", existing_type=sa.VARCHAR(), nullable=False, schema="gtfs"
    )
    op.alter_column(
        "shapes",
        "shape_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
        schema="gtfs",
    )
    op.create_index(
        op.f("ix_gtfs_shapes_feed_id"),
        "shapes",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.execute("""
               WITH ranked AS (
                SELECT ctid,
                        ROW_NUMBER() OVER (
                        PARTITION BY feed_id, shape_id, shape_pt_sequence
                        ORDER BY ctid
                        ) AS rn
                from gtfs.shapes
                )
                DELETE from gtfs.shapes
                WHERE ctid IN (
                SELECT ctid FROM ranked WHERE rn > 1
                );
               """)
    op.create_unique_constraint(
        "uq_shape_feed_shape_sequence",
        "shapes",
        ["feed_id", "shape_id", "shape_pt_sequence"],
        schema="gtfs",
    )
    logger.info("Stop_times table updates")
    _add_sequence_pk("stop_times")
    op.add_column(
        "stop_times",
        sa.Column("continuous_pickup", sa.Integer(), nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "stop_times",
        sa.Column("continuous_drop_off", sa.Integer(), nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "stop_times",
        sa.Column("shape_dist_traveled", sa.Float(), nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "stop_times", sa.Column("timepoint", sa.Integer(), nullable=True), schema="gtfs"
    )
    op.alter_column(
        "stop_times",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="gtfs",
    )
    op.create_index(
        op.f("ix_gtfs_stop_times_feed_id"),
        "stop_times",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.create_unique_constraint(
        "uq_stop_time_feed_trip_stop_sequence",
        "stop_times",
        ["feed_id", "trip_id", "stop_id", "stop_sequence"],
        schema="gtfs",
    )
    logger.info("Stops table updates")
    _add_sequence_pk("stops")
    op.add_column(
        "stops", sa.Column("zone_id", sa.String(), nullable=True), schema="gtfs"
    )
    op.add_column(
        "stops", sa.Column("stop_url", sa.Text(), nullable=True), schema="gtfs"
    )
    op.add_column(
        "stops", sa.Column("stop_timezone", sa.String(), nullable=True), schema="gtfs"
    )
    op.add_column(
        "stops", sa.Column("level_id", sa.String(), nullable=True), schema="gtfs"
    )
    op.alter_column(
        "stops", "feed_id", existing_type=sa.VARCHAR(), nullable=False, schema="gtfs"
    )
    op.create_index(
        op.f("ix_gtfs_stops_feed_id"), "stops", ["feed_id"], unique=False, schema="gtfs"
    )
    op.create_unique_constraint(
        "uq_stop_feed_stop_id", "stops", ["feed_id", "stop_id"], schema="gtfs"
    )
    logger.info("Transfers table updates")
    _add_sequence_pk("transfers")
    op.alter_column(
        "transfers",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="gtfs",
    )
    op.create_index(
        op.f("ix_gtfs_transfers_feed_id"),
        "transfers",
        ["feed_id"],
        unique=False,
        schema="gtfs",
    )
    op.create_unique_constraint(
        "uq_transfer_feed_from_to_stop",
        "transfers",
        ["feed_id", "from_stop_id", "to_stop_id", "from_route_id", "to_route_id"],
        schema="gtfs",
    )
    logger.info("Trips table updates")
    _add_sequence_pk("trips")
    op.alter_column(
        "trips", "feed_id", existing_type=sa.VARCHAR(), nullable=False, schema="gtfs"
    )
    op.create_index(
        op.f("ix_gtfs_trips_feed_id"), "trips", ["feed_id"], unique=False, schema="gtfs"
    )
    op.create_unique_constraint(
        "uq_trip_feed_trip_id", "trips", ["feed_id", "trip_id"], schema="gtfs"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    def _drop_sequence(table: str) -> None:
        op.execute(f"DROP SEQUENCE IF EXISTS gtfs.{table}_id_seq")

    op.drop_constraint("uq_trip_feed_trip_id", "trips", schema="gtfs", type_="unique")
    op.drop_index(op.f("ix_gtfs_trips_feed_id"), table_name="trips", schema="gtfs")
    op.alter_column(
        "trips", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_constraint("pk_trips", "trips", schema="gtfs", type_="primary")
    op.drop_column("trips", "id", schema="gtfs")
    _drop_sequence("trips")
    op.add_column(
        "transfers",
        sa.Column("from_route_id", sa.TEXT(), autoincrement=False, nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "transfers",
        sa.Column("from_trip_id", sa.TEXT(), autoincrement=False, nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "transfers",
        sa.Column("to_route_id", sa.TEXT(), autoincrement=False, nullable=True),
        schema="gtfs",
    )
    op.add_column(
        "transfers",
        sa.Column("to_trip_id", sa.TEXT(), autoincrement=False, nullable=True),
        schema="gtfs",
    )
    op.drop_constraint(
        "uq_transfer_feed_from_to_stop", "transfers", schema="gtfs", type_="unique"
    )
    op.drop_index(
        op.f("ix_gtfs_transfers_feed_id"), table_name="transfers", schema="gtfs"
    )
    op.alter_column(
        "transfers", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_constraint("pk_transfers", "transfers", schema="gtfs", type_="primary")
    op.drop_column("transfers", "id", schema="gtfs")
    _drop_sequence("transfers")
    op.drop_constraint("uq_stop_feed_stop_id", "stops", schema="gtfs", type_="unique")
    op.drop_index(op.f("ix_gtfs_stops_feed_id"), table_name="stops", schema="gtfs")
    op.alter_column(
        "stops", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_constraint("pk_stops", "stops", schema="gtfs", type_="primary")
    op.drop_column("stops", "level_id", schema="gtfs")
    op.drop_column("stops", "stop_timezone", schema="gtfs")
    op.drop_column("stops", "stop_url", schema="gtfs")
    op.drop_column("stops", "zone_id", schema="gtfs")
    op.drop_column("stops", "id", schema="gtfs")
    _drop_sequence("stops")
    op.drop_constraint(
        "uq_stop_time_feed_trip_stop_sequence",
        "stop_times",
        schema="gtfs",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_gtfs_stop_times_feed_id"), table_name="stop_times", schema="gtfs"
    )
    op.alter_column(
        "stop_times",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="gtfs",
    )
    op.drop_constraint("pk_stop_times", "stop_times", schema="gtfs", type_="primary")
    op.drop_column("stop_times", "timepoint", schema="gtfs")
    op.drop_column("stop_times", "shape_dist_traveled", schema="gtfs")
    op.drop_column("stop_times", "continuous_drop_off", schema="gtfs")
    op.drop_column("stop_times", "continuous_pickup", schema="gtfs")
    op.drop_column("stop_times", "id", schema="gtfs")
    _drop_sequence("stop_times")
    op.drop_constraint(
        "uq_shape_feed_shape_sequence", "shapes", schema="gtfs", type_="unique"
    )
    op.drop_index(op.f("ix_gtfs_shapes_feed_id"), table_name="shapes", schema="gtfs")
    op.alter_column(
        "shapes",
        "shape_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="gtfs",
    )
    op.alter_column(
        "shapes", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_column("shapes", "shape_dist_traveled", schema="gtfs")
    op.drop_constraint("pk_shapes", "shapes", schema="gtfs", type_="primary")
    op.drop_column("shapes", "id", schema="gtfs")
    _drop_sequence("shapes")
    op.drop_constraint(
        "uq_route_feed_route_id", "routes", schema="gtfs", type_="unique"
    )
    op.drop_index(op.f("ix_gtfs_routes_feed_id"), table_name="routes", schema="gtfs")
    op.alter_column(
        "routes", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_column("routes", "continuous_drop_off", schema="gtfs")
    op.drop_column("routes", "continuous_pickup", schema="gtfs")
    op.drop_column("routes", "route_sort_order", schema="gtfs")
    op.drop_column("routes", "route_url", schema="gtfs")
    op.drop_constraint("pk_routes", "routes", schema="gtfs", type_="primary")
    op.drop_column("routes", "id", schema="gtfs")
    _drop_sequence("routes")
    op.drop_index(
        op.f("ix_gtfs_frequencies_feed_id"), table_name="frequencies", schema="gtfs"
    )
    op.alter_column(
        "frequencies",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="gtfs",
    )
    op.drop_constraint("pk_frequencies", "frequencies", schema="gtfs", type_="primary")
    op.drop_column("frequencies", "id", schema="gtfs")
    _drop_sequence("frequencies")
    op.add_column(
        "feed_info",
        sa.Column("feed_contact_mail", sa.TEXT(), autoincrement=False, nullable=True),
        schema="gtfs",
    )
    op.drop_index(
        op.f("ix_gtfs_feed_info_feed_id"), table_name="feed_info", schema="gtfs"
    )
    op.alter_column(
        "feed_info", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_column("feed_info", "feed_contact_email", schema="gtfs")
    op.drop_constraint("pk_feed_info", "feed_info", schema="gtfs", type_="primary")
    op.drop_column("feed_info", "id", schema="gtfs")
    _drop_sequence("feed_info")
    op.drop_constraint(
        "uq_calendar_date_feed_service_date",
        "calendar_dates",
        schema="gtfs",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_gtfs_calendar_dates_feed_id"),
        table_name="calendar_dates",
        schema="gtfs",
    )
    op.alter_column(
        "calendar_dates",
        "feed_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="gtfs",
    )
    op.drop_constraint(
        "pk_calendar_dates", "calendar_dates", schema="gtfs", type_="primary"
    )
    op.drop_column("calendar_dates", "id", schema="gtfs")
    _drop_sequence("calendar_dates")
    op.drop_constraint(
        "uq_calendar_feed_service_id", "calendar", schema="gtfs", type_="unique"
    )
    op.drop_index(
        op.f("ix_gtfs_calendar_feed_id"), table_name="calendar", schema="gtfs"
    )
    op.alter_column(
        "calendar",
        "service_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        nullable=True,
        schema="gtfs",
    )
    op.alter_column(
        "calendar", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_constraint("pk_calendar", "calendar", schema="gtfs", type_="primary")
    op.drop_column("calendar", "id", schema="gtfs")
    _drop_sequence("calendar")
    op.drop_constraint(
        "uq_agency_feed_agency_id", "agency", schema="gtfs", type_="unique"
    )
    op.drop_index(op.f("ix_gtfs_agency_feed_id"), table_name="agency", schema="gtfs")
    op.alter_column(
        "agency",
        "agency_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        nullable=True,
        schema="gtfs",
    )
    op.alter_column(
        "agency", "feed_id", existing_type=sa.VARCHAR(), nullable=True, schema="gtfs"
    )
    op.drop_constraint("pk_agency", "agency", schema="gtfs", type_="primary")
    op.drop_column("agency", "id", schema="gtfs")
    _drop_sequence("agency")
    # ### end Alembic commands ###
